name: Releaser

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build and Release Extension
    runs-on: windows-2025-vs2026

    permissions:
      artifact-metadata: write
      attestations: write
      contents: write
      id-token: write
      packages: write

    defaults:
      run:
        shell: pwsh

    env:
      USERNAME: korarei
      FEED_URL: https://nuget.pkg.github.com/korarei/index.json
      VCPKG_BINARY_SOURCES: clear;nuget,https://nuget.pkg.github.com/korarei/index.json,readwrite

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Add NuGet sources
      run: |
        $nuget = & "$env:VCPKG_ROOT\vcpkg.exe" fetch nuget

        & $nuget sources add `
          -Source $env:FEED_URL `
          -StorePasswordInClearText `
          -Name GitHubPackages `
          -UserName $env:USERNAME `
          -Password "${{ secrets.GITHUB_TOKEN }}"

        & $nuget setapikey `
          "${{ secrets.GITHUB_TOKEN }}" `
          -Source $env:FEED_URL

    - name: Install dependencies & Build extension
      run: |
        python -m pip install git+https://github.com/korarei/AviUtl2_Astra.git@v0.6.5

        $version = $env:GITHUB_REF_NAME.Substring(1)
        astra release -v $version

    - name: Generate Artifact Attestation
      uses: actions/attest@v4
      with:
        subject-path: release/*.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        name: "${{ github.ref_name }}"
        files: release/*.zip
        body_path: release/release_notes.md
